f = open("demofile.txt", "w")
f.write("Hello World\n")
f.write("This is our new text file\n")
f.close()
f = open("demofile.txt", "r")
print(f.read())
f.close()
f = open("demofile.txt", "a")
f.write("This is the fresh text.\n")
f.close()
f = open("demofile.txt", "r")
print(f.read())
f = open("demofile.txt", "r")
lines = f.readlines()
f.close()
new_lines = [line.replace("Hello", "Vanakkam") for line in lines]
f = open("demofile.txt", "w")
f.writelines(new_lines)
f.close()